
myName = input ("Whats Your name?")
myAge = input ("How old are you")
print("wow you look older")
myYear = input ("what year where you born")
print("wow that sound super old")
print ()
print ("Okay so you are")
print (myName)
print ("And your age")
print (myAge)
print (" And you where born in")
print (myYear)
print ("Nice to meet you")
# Much more progress learned how to ask question questions than later on collect all the data and do the output all at once.